name: flutter_ui_example
description: An app showcasing Flutter components, with side-by-side source code view.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 4.3.8
  cupertino_icons: ^1.0.2
  backdrop: ^0.6.2
  provider: ^6.0.1

  mmkv: ">=1.2.11"
  #代码显示工具
  widget_with_codeview: ^2.0.0-nullsafe
  day_night_switcher: ^0.2.0+1
  substring_highlight: ^1.0.33
  badges: ^2.0.1
  #图片请求
  cached_network_image: 3.1.0

  flutter_screenutil: 5.0.0+2

  flutter_gallery_assets: ^1.0.2
  shared_preferences: ^2.0.6

  fluttertoast: 8.0.8

  # https://github.com/flutterchina/flukit.
  flukit: ^2.0.0
  webview_flutter: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.6
  flutter_native_splash: ^1.2.0
  freezed: ^0.14.2
  hive_generator: ^1.1.0
  json_serializable:
  lint: ^1.5.3
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_native_splash:
  color: "#f6f6f6"
  image: assets/images/splash_screen.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # Note: when new assets are added, have to run `flutter clean` to see
  # changes take effect.
  assets:
    # *Tip*: keep the slash at the end of folder path adds all files to
    # assets. Note: this doesn't work with subfolders.
    # c.f. https://github.com/flutter/flutter/issues/4890#issuecomment-407327749
    - lib/modular/
    - lib/modular/widgets/
    - lib/modular/animation/
    - lib/modular/data/
    - lib/modular/search/
    - lib/modular/splash/
 #   - lib/modular/data
    - assets/images/
    - assets/lottie/
